### PR TITLE
OT Interceptor can leak if repeatedly resolving dependent beans.

### LINKED ISSUE #9: OpenTracingInterceptor memory leak
As reported in a [WildFly issue](https://issues.redhat.com/browse/WFLY-14094), there can be a memory leak related to `OpenTracingInterceptor` and it's repeated resolution of `Tracer` bean. In case the `@Traced` bean is of wider scope (such as `@ApplicationScoped`) and the `Tracer` bean is `@Dependent`, this interceptor will repeatedly resolve the same bean and hence create new instances of it.

See the linked issue for details and a reproducer.

There are two solutions to it:

1. Implement caching which gives more performance since you only need to create bean once. This presumes OT doesn't need to repeatedly create `Tracer` bean for once object which from my understanding should work. Though I am no expert on OT, so please correct me if I am wrong.
2. Implement proper bean destruction at the end of interception. This is basically using `Instance.destroy()` method at the end *iff* the bean is dependent. Doable but will be worse in perf since you still need to construct bean on every call and now you also need to destroy it (which in most impls should be no-op?).

I will go ahead and submit a PR for the 1. solution which I think is better.

### PR DESCRIPTION
**Pull request by manovotn**
Fixes #9 

Please see the above issue and/or [WildFly](https://issues.redhat.com/browse/WFLY-14094) issue for more details.

Cc @mkouba for second pair of CDI-trained eyes ;-)

### CODE REVIEW

**Review by mkouba — APPROVED** [review]
Looks good now ;-).

**Comment by manovotn** [comment]
I have updated the PR to include a volatile field and synchronized access when you first set the value into it (thanks Martin!).
This avoids race condition if the interceptor operates on something like application scoped bean which is accessed by several threads simultaneously. It is a corner case but we should take it into consideration. The impl will avoid the synchronized block in 99% cases so it's basically just one volatile read.

**Review by jpkrohling — APPROVED** [review]
The change looks sane to me, but CI failed. I started it again just in case.

**Comment by manovotn** [comment]
Hmm, the failure from last log looks pretty unrelated. Pretty cryptic too :-D
```
Caused by: java.lang.RuntimeException: Class java/lang/UnknownError could not be instrumented.

	at org.jacoco.agent.rt.internal_c13123e.core.runtime.ModifiedSystemClassRuntime.createFor(ModifiedSystemClassRuntime.java:140)

	at org.jacoco.agent.rt.internal_c13123e.core.runtime.ModifiedSystemClassRuntime.createFor(ModifiedSystemClassRuntime.java:101)

	at org.jacoco.agent.rt.internal_c13123e.PreMain.createRuntime(PreMain.java:55)

	at org.jacoco.agent.rt.internal_c13123e.PreMain.premain(PreMain.java:47)

	... 6 more

Caused by: java.lang.NoSuchFieldException: $jacocoAccess
```

**Comment by manovotn** [comment]
@jpkrohling actually, I think I know what's the error related to.
Didn't Travis update their images to JDK 11 recently? You config file doesn't seem to state JDK version and I am seeing the exact same error when building locally with JDK 11. JDK 8 passes fine (using `./gradlew build`).
And this happens on current master regardless of this PR.

Though I am a Gradle noob, so don't ask me what's the actual problem behind that...

**Comment by jpkrohling** [comment]
That might indeed be the case. I'll trigger a build for the current master to check.

**Comment by jpkrohling** [comment]
Master does seem to work: https://travis-ci.org/github/opentracing-contrib/java-interceptors/builds/546808524

Edit: while master did work, it was using an older Java version.

Build for this PR:
```
$ java -Xmx32m -version
openjdk version "11.0.2" 2019-01-15
OpenJDK Runtime Environment 18.9 (build 11.0.2+9)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.2+9, mixed mode)
```

Build for master:
```
$ java -Xmx32m -version
java version "1.8.0_151"
Java(TM) SE Runtime Environment (build 1.8.0_151-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.151-b12, mixed mode)
```

**Comment by jpkrohling** [comment]
Opened #11 to get around the unpredictable JDK version.

**Comment by jpkrohling** [comment]
Thanks for the PR!

**Pull request merged**
