### PR TITLE
Bumping up Open Tracing dependencies

### PR DESCRIPTION
**Pull request by kasinskim**
## Description
Bumping up Open Tracing dependencies:
- upgrading Open Tracing API  to latest available (`0.33.0`)
- upgrading OT TracerResolver to latest available (`0.1.8`)
- adopting `OpenTracingInterceptor` implementation that was affected by API changes

### CODE REVIEW

**Comment by kasinskim** [comment]
@jpkrohling Any chance of reviewing/accepting this PR?

**Review by jpkrohling — APPROVED** [review]

**Comment by jpkrohling** [comment]
Thanks!

**Comment by jpkrohling** [comment]
How soon would you need a release with this fix, @kasinskim?

**Comment by kasinskim** [comment]
@jpkrohling This is the last thing that I need to upgrade to have OT API (0.33.0) in my codebase. 
So, if that's not a problem - the sooner the release the better. Thanks.

**Comment by jpkrohling** [comment]
0.0.5 was just released and the artifacts should reach Maven Central in a few minutes (up to one hour).

**Comment by kasinskim** [comment]
Thanks a lot!

**Pull request merged**
