### PR TITLE
Remove shipkit

### PR DESCRIPTION
**Pull request by jpkrohling**
Signed-off-by: Juraci Paixão Kröhling <juraci@kroehling.de>

### CODE REVIEW

**Comment by pavolloffay** [comment]
just for curiosity: why removing shipkit? 

I wanted to give it a try in another project since the bintray plugin tends to fail.

**Comment by jpkrohling** [comment]
For some reason, we need to release a version like `0.0.4.1` and shipkit doesn't support it (perhaps correctly, as it's not really semver). The workaround is to release something like 0.0.4-patch.1, but that didn't work at first either. As I'm having trouble finding documentation for the version we were using, I thought I'd rather then just use the regular approach.

I just updated the RELEASE.md with the current instructions, but I'm yet to verify that the automation works. It also includes a possible fix for the "multiple staging repos" problem that we've seen in other projects (hint: look at gradle.properties, as it "fixes" part of the problem).

**Comment by jpkrohling** [comment]
Just to record my saga in publishing a single Java source file + a pom.xml:

1. Due to the latest Travis changes, it was taking about a couple of hours for the release build to be triggered. Instead of waiting for a couple of hours for each attempt, possibly for a few attempts, I decided to move to GitHub Actions
1. In the process, I hit the Shipkit problem I described above
1. I also noticed that the "release commits" from Shipkit weren't being pushed to master. Like this: https://github.com/opentracing-contrib/java-interceptors/commit/2eb7efd272b82c568726420a7c559702435917a3
1. I thought: "it's 2020, there's probably an easy way to release Java libraries by now"
1. Reading the Gradle documentation, I used their template. There was also a documentation page on GitHub Actions docs that was helpful here. 
1. Publishing a release as a GitHub package was straightforward. See the "packages" in this repo.
1. But not for Nexus. The "multiple staging repositories" problem still exists. It also still requires the build to create the checksums and signatures. Apparently, it can't trust the credentials we send them, so, they can't create those files for us.
1. "It's 2020, Gradle certainly fixed the multiple staging repos problem in the meantime". Upgrade to Gradle 6.7.x should work.
1. Nope.
1. I did come up with a way to release to Sonatype's Nexus eventually. But look at the list of releases we have in this repo now... Pretty much *all* of them are related to everything but the Java source file + pom.xml...
1. I also decided to remove the publishing of packages as a GitHub package. The reason is that Nexus is idempotent, whereas GitHub packages aren't. While GitHub packages seems to be reliable, Nexus isn't (and we need things in Maven Central, unfortunately). As I do think we'll need to restart the release jobs in the future, I removed the publishing to GitHub packages

The end result is that it now works: https://github.com/opentracing-contrib/java-interceptors/runs/1463763118?check_suite_focus=true

**Comment by pavolloffay** [comment]
thanks for the write-up. Maybe another 10 years and we will have easy release process in Java, or maybe there won't be java.

**Pull request merged**
